GET http://localhost:3030/travel HTTP/1.1

###

Get http://localhost:3030/travel/api/country


###
Get http://localhost:3030/travel/api/country/
###
Get http://localhost:3030/travel/usa
###
POST http://localhost:3030/travel
Content-type: application/json

{
   "name": "sweden",
   "city": [{
      "cityname": "stokholm",
      "citySight": ["Gamla Stan","Vasa Museum","Djurgården"],
      "disc": "Often called the 'Venice of the North' for its waterways and lakes, Stockholm, the capital city of Sweden",
      "hotels": ["Hilton Stockholm Slussen", "Generator Stockholm","Grand Hôtel", "Clarion Hotel Stockholm"],
      "restaurants": ["Enskede Rackethall","Stockholms Gästabud" , "Den Gyldene Freden"],
      "crimeRate": "51.24	Moderate",
      "rate": 4.2
   },
   {
     "cityname": "Ystad",
      "citySight": ["Saint Petri’s Church ","Grey Friar’s Monastery","Saint Petri’s mussem"],
      "disc": "Ystad is a town made well-known by the Kurt Wallander novels, which have been interpreted into English and adapted into several cinemas, ",
      "hotels": ["Continental du Sud","Stora Herrestad Bed & Breakfast","Hotell Mossbylund"],
      "restaurants": ["Villa Strandvägen", "Grändens mat", "Saluhallen Ystad"],
      "crimeRate": "31.54	Moderate",
      "rate": 4
   }],
   "website":"https://visitsweden.com/",
   "food": ["Köttbullar, meat balls", "Janssons Frestelse, Jansson's temptation","Smörgåstårta, sandwich cake"],
   "sight": ["Smörgåstårta, sandwich cake", "Operan (The Royal Opera)", "Skeppsholmen Island","Lapland"],
   "visitings": 35200000,
   "language":["Swedish"," Greek","English"]
}

###
POST http://localhost:3030/travel/api/country/
Content-Type: application/json

{
   "name": "sweden",
   "city": [{
      "cityname": "stokholm",
      "citySight": ["Gamla Stan","Vasa Museum","Djurgården"],
      "disc": "Often called the 'Venice of the North' for its waterways and lakes, Stockholm, the capital city of Sweden",
      "hotels": ["Hilton Stockholm Slussen", "Generator Stockholm","Grand Hôtel", "Clarion Hotel Stockholm"],
      "restaurants": ["Enskede Rackethall","Stockholms Gästabud" , "Den Gyldene Freden"],
      "crimeRate": "51.24 Moderate",
      "rate": 4
   },
   {
     "cityname": "Ystad",
      "citySight": ["Saint Petri’s Church ","Grey Friar’s Monastery","Saint Petri’s mussem"],
      "disc": "Ystad is a town made well-known by the Kurt Wallander novels, which have been interpreted into English and adapted into several cinemas, ",
      "hotels": ["Continental du Sud","Stora Herrestad Bed & Breakfast","Hotell Mossbylund"],
      "restaurants": ["Villa Strandvägen", "Grändens mat", "Saluhallen Ystad"],
      "crimeRate": "31.54 Moderate",
      "rate": 4
   }],
   "website":"https://visitsweden.com/",
   "food": ["Köttbullar, meat balls", "Janssons Frestelse, Jansson's temptation","Smörgåstårta, sandwich cake"],
   "sight": ["Smörgåstårta, sandwich cake", "Operan (The Royal Opera)", "Skeppsholmen Island","Lapland"],
   "visitings": 35200000,
   "languages":["Swedish"," Greek","English"]
}

###
DELETE  http://localhost:3030/travel/62abd491efb59377fe8fb87e
###

DELETE  http://localhost:3030/travel/api/country/62b0b3cf4b5426adef4ff8ff
###
GET   http://localhost:3030/travel/api/country/spain
###
PATCH  http://localhost:3030/travel/api/country/egypt
Content-Type: application/json

{
   "website":"https://www.egypttoursportal.com/"
}
###
PATCH  http://localhost:3030/travel/egypt
Content-Type: application/json

{
   "food":"name"
}