GET http://localhost:8888/travel

###

Get http://localhost:8888/travel/api/country


###
Get http://localhost:8888/travel/api/country/usa
###
Get http://localhost:8888/travel/usa
###
POST http://localhost:8888/travel/
Content-Type: application/json

{
   "name": "usa",
   "city": ["new York","washington",""],
   "food": ["atay", "koskos"],
   "sight": ["none"],
   "visitings": 12000
}

###
POST http://localhost:8888/travel/api/country
Content-Type: application/json

{
   "name": "morocco",
   "city": ["marrakech","casablanca"],
   "food": ["atay", "koskos"],
   "sight": ["none"]
}

###
DELETE  http://localhost:8888/travel/api/country/usa
###
Get http://localhost:8888/travel/usa