GET http://localhost:8888/travel HTTP/1.1

###

Get http://localhost:8888/travel/api/country


###
Get http://localhost:8888/travel/api/country/usa
###
Get http://localhost:8888/travel/usa
###
POST http://localhost:8888/travel
Content-Type: application/json

{
   "name": "france",
   "city": {
      "name": "paris",
      "sight": ["none","none"],
      "disc": "good city for visiting a old country",
      "restaurants": ["reda", "red", "one"],
      "hotels": ["hotel", "hot"],
      "crimeRate": 24000,
      "rate": 4.6,
   },
   "food": ["bread", "bouillabaise"],
   "sight": ["eiffel", "mousem"],
   "visitings": 780000000,
}

###
POST http://localhost:8888/travel/api/country/
Content-Type: application/json

{
   "name": "france",
   "city": {
      "name": "paris",
      "sight": ["none","none"],
      "disc": "good city for visiting a old country",
      "restaurants": ["reda", "red", "one"],
      "hotels": ["hotel", "hot"],
      "crimeRate": 24000,
      "rate": 4.6,
   },
   "food": ["bread", "bouillabaise"],
   "sight": ["eiffel", "mousem"],
   "visitings": 780000000,
}

###
DELETE  http://localhost:8888/travel/api/country/usa
###
Get http://localhost:8888/travel/usa